### ISSUE TITLE
flutter_gherkin_integration_test.dart not found in 3.0.0-rc.2 package

### ISSUE THREAD

**Issue by JessWeston** [jonsamwell/flutter_gherkin#135]
I am trying to experiment with flutter_gherkin for integration test in flutter_gherkin 3.0.0-rc2 pre-release. The Readme.md suggests I should import the `package:flutter_gherkin/flutter_gherkin_integration_test.dart`, but in my gherkin_test_suite.dart file this is not found.

My pubspec.yaml contains the following:
```
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner:
  flutter_gherkin: ^3.0.0-rc.2
```

Its seems my environment has flutter_gherkin-2.0.0 as well, though this is not in my pubspec.yaml file:
```
pub.dartlang.org [stable] % ls flutter_gherkin*
flutter_gherkin-2.0.0:
CHANGELOG.md           analysis_options.yaml  pre-publish-checks.cmd
LICENSE                example                pubspec.yaml
README.md              lib                    test

flutter_gherkin-3.0.0-rc.2:
CHANGELOG.md                  example_with_integration_test
LICENSE                       flutter_cucumber.iml
README.md                     lib
analysis_options.yaml         pre-publish-checks.cmd
build.yaml                    pubspec.yaml
example_with_flutter_driver   test
```

Am I missing something here, this seems like a really obvious error, so it really could be I missed something in the Readme.md for set up?
