### ISSUE TITLE
Scenario with same matcher will run the first match.

### ISSUE THREAD

**Issue by zaralockheart** [jonsamwell/flutter_gherkin#137]
Hi, thanks for making it available for integration_test.

gherkin version that I am using:
```
flutter_gherkin:
    git:
      url: https://github.com/jonsamwell/flutter_gherkin.git
      ref: 5f0201101ec44ad5d9d196cff8c23f849f56ea09
```

 I know that this is expected `gherkin_integration_test_runner.dart`
```
final executable = _executableSteps.firstWhere(
      (s) => s.expression.isMatch(step),
      orElse: () => null,
    );
```

but I have scenarios like `I expect to view Dashboard` and `I expect to view Dashboard with action` and when I am expecting it to run `I expect to view Dashboard with action`, it run `I expect to view Dashboard`.
