### ISSUE TITLE
VMServiceFlutterDriver: It is taking an unusually long time to connect to the VM...

### ISSUE THREAD

**Issue by aliakbr** [jonsamwell/flutter_gherkin#151]
Hi all, I am experiencing a very weird issue. I've pulled the example code from this repo and successfully run the example code. Meanwhile, after copying the example code to my current repo project I am facing this issue :

```
MServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:41469/fHuAGuubaqw=/
VMServiceFlutterDriver: It is taking an unusually long time to connect to the VM...
VMServiceFlutterDriver: It is taking an unusually long time to connect to the VM...
VMServiceFlutterDriver: It is taking an unusually long time to connect to the VM...
VMServiceFlutterDriver: It is taking an unusually long time to connect to the VM...
VMServiceFlutterDriver: It is taking an unusually long time to connect to the VM...
```

It seems like the flutter driver can't connect to. any of my simulator/devices in this project. This is some detail of my environment and how to run the test :

flutter doctor :
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.4 20F71 darwin-x64, locale
    en-ID)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Community Edition (version 2020.1.2)
[✓] VS Code (version 1.60.1)
[✓] Connected device (2 available)
```

Project structure (test_driver folder):
```
.
├── app.dart
├── app_test.dart
├── features
│   └── login.feature
├── hook
│   └── hook_example.dart
├── report.json
```

app.dart (test_driver)
```
import 'package:flutter_driver/driver_extension.dart';
import 'package:frontend/main_test.dart' as app;  // Change to your main app

void main() {
  enableFlutterDriverExtension();

  // Switch services impls to mock services
  app.main();
}
```

app_test.dart (test_driver)
```
import 'dart:async';
import 'package:flutter_gherkin/flutter_gherkin.dart';
import 'package:gherkin/gherkin.dart';

Future<void> main() {
  final config = FlutterTestConfiguration.DEFAULT(
    [],
    featurePath: 'features/*.*.feature',
    targetAppPath: 'test_driver/app.dart',
  )
  // ..logFlutterProcessOutput = true
  // ..verboseFlutterProcessLogs = true
    ..restartAppBetweenScenarios = true
    ..targetAppWorkingDirectory = '../'
    ..targetAppPath = 'test_driver/app.dart';
  // ..buildFlavor = "staging" // uncomment when using build flavor and check android/ios flavor setup see android file android\app\build.gradle
  // ..targetDeviceId = "all" // uncomment to run tests on all connected devices or set specific device target id
  // ..tagExpression = '@smoke and not @ignore' // uncomment to see an example of running scenarios based on tag expressions
  // ..logFlutterProcessOutput = true // uncomment to see command invoked to start the flutter test app
  // ..verboseFlutterProcessLogs = true // uncomment to see the verbose output from the Flutter process
  // ..flutterBuildTimeout = Duration(minutes: 3) // uncomment to change the default period that flutter is expected to build and start the app within
  // ..runningAppProtocolEndpointUri =
  //     'http://127.0.0.1:51540/bkegoer6eH8=/' // already running app observatory / service protocol uri (with enableFlutterDriverExtension method invoked) to test against if you use this set `restartAppBetweenScenarios` to false

  return GherkinRunner().execute(config);
}
```
login.feature
```
Feature: Login into app

  Scenario: Splash Screen should appear
    Then I wait until the "splashScreen" is present
```

This is my app code :
main_test.dart
```
import 'package:flutter/material.dart';

import 'app_test.dart';

void main() {
  runApp(MyApp());
}
```

app_test.dart
```
import 'package:flutter/material.dart';

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Counter App',
      home: MyHomePage(key: Key('splashScreen'), title: 'Counter App Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  bool hasLongPressedText = false;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      drawer: Drawer(
        key: const Key('drawer'),
        child: ListView(
          padding: EdgeInsets.zero,
          children: <Widget>[
            DrawerHeader(
              decoration: BoxDecoration(
                color: Colors.blue,
              ),
              child: const Text('Drawer Header'),
            ),
            ListTile(
              title: const Text('Item 1'),
              onTap: () {
                // Update the state of the app
                // ...
                // Then close the drawer
                Navigator.pop(context);
              },
            ),
            ListTile(
              title: const Text('Item 2'),
              onTap: () {
                // Update the state of the app
                // ...
                // Then close the drawer
                Navigator.pop(context);
              },
            ),
          ],
        ),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              // Provide a Key to this specific Text Widget. This allows us
              // to identify this specific Widget from inside our test suite and
              // read the text.
              key: const Key('counter'),
              style: Theme.of(context).textTheme.headline4,
            ),
            TextButton(
              key: Key('openPage2'),
              onLongPress: () {
                Future.delayed(
                    Duration(seconds: 12),
                        () => Navigator.push(
                      context,
                      MaterialPageRoute(builder: (context) => PageTwo()),
                    ));
              },
              onPressed: () {
                Navigator.push(
                  context,
                  MaterialPageRoute(builder: (context) => PageTwo()),
                );
              },
              child: Text('Open page 2'),
            ),
            GestureDetector(
              onLongPress: () {
                setState(() {
                  hasLongPressedText = true;
                });
              },
              child: Container(
                color:
                hasLongPressedText ? Colors.blueGrey : Colors.transparent,
                child: Text(
                  hasLongPressedText
                      ? 'Text has been long pressed!'
                      : 'Text that has not been long pressed',
                  key: const Key('longPressText'),
                ),
              ),
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        // Provide a Key to this the button. This allows us to find this
        // specific button and tap it inside the test suite.
        key: const Key('increment'),
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

class PageTwo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      key: Key('pageTwo'),
      appBar: AppBar(
        automaticallyImplyLeading: true,
        title: Text('Page 2'),
      ),
      body: SafeArea(
        child: Center(
          child: Text('Contents of page 2'),
        ),
      ),
    );
  }
}
```

pubspec.yaml
```
name: frontend
description: App Description

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.3.7
versionProd: 1.3.6

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^2.0.0
  flutter_feather_icons: ^2.0.0+1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get_it: ^7.1.3
  provider: ^5.0.0
  firebase_analytics: ^8.3.1
  firebase_core: ^1.6.0
  flutter_secure_storage: ^4.2.0
  flutter_dotenv: ^4.0.0-nullsafety.1
  environment_config: ^3.0.0
  intl: ^0.17.0
  blobs: ^2.0.0
  sentry_flutter: ^6.0.0
  #flutter_segment: ^3.1.0
  flutter_segment:
    git: https://github.com/gotlostinparadise/flutter-segment.git
  video_player: ^2.1.1
  better_player: ^0.0.72
  webview_flutter: ^2.0.4
  graphql: ^5.0.0-nullsafety.4
  flutter_native_timezone: ^2.0.0
  # wakelock Held back until chewie updates its wakelock dependency
  wakelock: ^0.5.2
  confetti: ^0.6.0-nullsafety
  stream_chat_flutter: ^2.0.0-nullsafety.4
  flutter_svg: ^0.22.0
  pedantic: ^1.11.0
  # keyboard_avoider: ^0.1.2 # unmaintained?
  # keyboard_avoider:
  #   git:
  #     url: https://github.com/KingsCards/keyboard_avoider.git
  #     ref: feature/null-safety
  keyboard_avoider:
    git:
      url: https://github.com/ryanheise/keyboard_avoider.git
      ref: fix/mounted-bug
  multi_image_picker: ^4.8.0
  path_provider: ^2.0.1
  dio: ^4.0.0
  styled_text: ^3.0.1
  scroll_to_index: ^2.0.0
  shimmer: ^2.0.0
  libphonenumber: ^2.0.0
  country_code_picker: ^2.0.1
  string_validator: ^0.3.0
  device_info: ^2.0.0
  # zendesk: ^2.0.0
  zendesk:
    git:
      url: https://github.com/ryanheise/flutter-zendesk.git
      ref: nnbd
  share: ^2.0.1
  upgrader: ^3.2.1
  in_app_update: ^2.0.0
  pin_code_fields: ^7.0.0
  firebase_messaging: ^10.0.6
  url_launcher: ^6.0.3
  adjust_sdk: ^4.29.0
  flutter_uxcam: ^2.0.0
  transparent_image: ^2.0.0
  firebase_remote_config: ^0.10.0+5
  awesome_emojis: ^0.1.1
  shared_preferences: ^2.0.6
  collection: ^1.15.0-nullsafety.4
  infinite_scroll_pagination: ^3.0.1+1
  in_app_review: ^2.0.2
  jiffy: ^4.1.0
  package_info: ^2.0.2
  moengage_flutter: ^4.0.2
  tutorial_coach_mark: ^1.0.3
  otp_autofill: ^1.1.0
  firebase_in_app_messaging: ^0.5.0+8
  storybook_flutter: ^0.5.1
  uni_links: ^0.5.1

dependency_overrides:
  # stream_chat_flutter depends on this while graphql is still pinned on 0.26.0.
  # Watch for updates on: https://github.com/zino-app/graphql-flutter/issues/899
  rxdart: ^0.27.0

dev_dependencies:
  intl_utils: 2.1.0
  flutter_launcher_icons: ^0.9.0
  mockito:
  build_runner:
  flutter_driver:
    sdk: flutter
  test: any
  flutter_test:
    sdk: flutter
  flutter_gherkin: ^2.0.0
  sentry_dart_plugin: ^1.0.0-alpha.2

sentry:
  upload_native_symbols: true
  include_native_sources: true
  upload_source_maps: true
  project: elevate-72
  org: kuncie
  wait_for_processing: true
  log_level: error
  auth_token: 0df4b034e8fd11ea8abe4201c0a8d039

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/mentors/
    - assets/experience/
    - assets/images/
    - assets/intro/
    - assets/onboarding/
    - assets/onboarding_small/
    - assets/library/
    - assets/ratings/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  main_locale: en_US
  enabled: true

# The adaptive foreground need extra padding for better look in android
# example https://github.com/fluttercommunity/flutter_launcher_icons/blob/master/example/default/assets/images/icon-foreground-432x432.png
# ref https://pub.dev/packages/flutter_launcher_icons
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "assets/icon/key_launch_background.png"
  adaptive_icon_foreground: "assets/icon/key_launch_icon.png"
```
