### ISSUE TITLE
TapWidgetOfTypeStep - Exception: type 'String' is not a subtype of type 'Type'

### ISSUE THREAD

**Issue by sebastiankutschbach** [jonsamwell/flutter_gherkin#164]
Hi,

can anyone tell me what I am doing wrong here?

**My scenario looks the following:**

```
Scenario: User can add set list
  Given A fresh app
  Given A logged in user
  When I tap the button of type "FloatingActionButton"
  When I fill the "setListName" field with "myNewlyCreatedList"
  When I tap the button that contains the text "Create"
  Then I expect the text "myNewlyCreatedList" to be present
```

**Test output is this:**

```
Running scenario: User can add set list # :0
   √ Given A fresh app # :0 took 14ms
   √ Given A logged in user # :0 took 5529ms
   × When I tap the button of type "FloatingActionButton" # :0 took 10ms  
Exception: type 'String' is not a subtype of type 'Type'
#0      WidgetTesterAppDriverAdapter.findBy (package:flutter_gherkin/src/flutter/adapters/widget_tester_app_driver_adapter.dart:177:28)
#1      TapWidgetOfTypeStep.<anonymous closure> (package:flutter_gherkin/src/flutter/steps/tap_widget_of_type_step.dart:18:33)
#2      TapWidgetOfTypeStep.<anonymous closure> (package:flutter_gherkin/src/flutter/steps/tap_widget_of_type_step.dart:16:5)
#3      Function._apply (dart:core-patch/function_patch.dart:11:73)
#4      Function.apply (dart:core-patch/function_patch.dart:34:12)
#5      GenericFunctionStepDefinition.onRun (package:gherkin/src/gherkin/steps/step_definition_implementations.dart:236:21)
#6      StepDefinitionGeneric.run.<anonymous closure> (package:gherkin/src/gherkin/steps/step_definition.dart:42:32)
#7      StepDefinitionGeneric.run.<anonymous closure> (package:gherkin/src/gherkin/steps/step_definition.dart:38:9)
#8      Perf.measure (package:gherkin/src/utils/perf.dart:11:26)
#9      StepDefinitionGeneric.run (package:gherkin/src/gherkin/steps/step_definition.dart:37:18)
#10     GherkinIntegrationTestRunner.runStep (package:flutter_gherkin/src/flutter/runners/gherkin_integration_test_runner.dart:283:42)
<asynchronous suspension>
#11     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart)
<asynchronous suspension>
PASSED: Scenario User can add set list # :0
running hook after scenario 'User can add set list'
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following _Exception was thrown running a test:
Exception: type 'String' is not a subtype of type 'Type'

When the exception was thrown, this was the stack:
#0      GherkinIntegrationTestRunner.runStep (package:flutter_gherkin/src/flutter/runners/gherkin_integration_test_runner.dart:299:7)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

The test description was:
  User can add set list
════════════════════════════════════════════════════════════════════════════════════════════════════

Test failed. See exception logs above.
The test description was: User can add set list
```

**My dependencies:**

```
dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  provider: ^6.0.1
  shared_preferences: ^2.0.8
  uri: ^1.0.0
  webview_flutter: ^2.1.2
  html: ^0.15.0
  url_launcher: ^6.0.12
  json_annotation: ^4.3.0
  cached_network_image: ^3.1.0

  cupertino_icons: ^1.0.3

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.4
  network_image_mock: ^2.0.1
  mocktail: ^0.2.0
  json_serializable: ^6.0.1
  flutter_dotenv: ^5.0.2
  flutter_lints: ^1.0.4
  flutter_gherkin: ^3.0.0-rc.6
```

Complete source code can be found [here](https://github.com/sebastiankutschbach/brick_app).

Thanks in advance!
