### ISSUE TITLE
build_runner does not gererate .g file in integration_test folder

### ISSUE THREAD

**Issue by 3lVv0w** [jonsamwell/flutter_gherkin#266]
i migrate from gherkin v2 -> 3 and follow the instruction i'm. currently stuck when to use
```
flutter pub run build_runner build --delete-conflicting-outputs
```

on model files it's working but nothings generate out on integration_test folder

**Comment by spaquis** [comment]
Hi @3lVv0w,
Did you add a build.yaml file in the root of the project with this content ?
```
targets:
  $default:
    sources:
      - lib/**
      - pubspec.*
      - $package$
      # Allows the code generator to target files outside of the lib folder
      - integration_test/**.dart

```
